- block:
  - name: Adds datastax debian repo key
    apt_key:
      url: https://debian.datastax.com/debian/repo_key
  - name: Adds datastax debian repo
    apt_repository:
      repo: "deb https://{{ dse_repository_login }}:{{ dse_repository_password }}@debian.datastax.com/enterprise stable main"
      update_cache: yes
  - name: Installs DSE
    apt:
      name: "{{dse_package}}"
      state: present
    notify:
      - Restart DSE
  when: ansible_os_family == "Debian"

- block:
  - name: Add datastax rpm repo key
    rpm_key:
      key: https://rpm.datastax.com/rpm/repo_key
  - name: Add datastax rpm repo
    yum_repository:
      name: dse
      description: Datastax YUM repo
      baseurl: "https://rpm.datastax.com/enterprise"
      username: "{{ dse_repository_login }}"
      password: "{{ dse_repository_password }}"
      enabled: yes
  - name: Install DSE
    yum:
      name: "{{dse_package}}"
      state: present
    notify:
      - Restart DSE
  when: ansible_os_family == "RedHat"

- include: create-folders.yml
  when: dse_install_dse

- name: Update cassandra.yaml
  template:
    src: cassandra.yaml.j2
    dest: /etc/dse/cassandra/cassandra.yaml
    backup: yes
    owner: cassandra
    group: cassandra
    mode: 0644
  tags: ["config","dse:config"]
  notify:
    - Restart DSE

- name: Update cassandra-rackdc.properties
  template:
    src: cassandra-rackdc.properties.j2
    dest: /etc/dse/cassandra/cassandra-rackdc.properties
    backup: yes
    owner: cassandra
    group: cassandra
    mode: 0644
  tags: ["config","dse:config"]
  notify:
    - Restart DSE

- name: Update cassandra-env.sh
  template:
    src: cassandra-env.sh.j2
    dest: /etc/dse/cassandra/cassandra-env.sh
    backup: yes
    owner: cassandra
    group: cassandra
    mode: 0644
  tags: ["config","dse:config"]
  notify:
    - Restart DSE

- name: Copy Default File for Instance
  template: 
    src: dse.j2 
    dest: /etc/sysconfig/dse
    mode: 0644 
    force: yes
  notify: 
    - Restart DSE

- name: Copy Config File for Instance
  template: 
    src: dse.conf.j2 
    dest: /usr/lib/sysctl.d/dse.conf
    mode: 0644 
    force: yes
  notify: 
    - Restart DSE

- name: Copy Systemd File for Instance
  template: 
    src: systemd/cassandra.service.j2 
    dest: /usr/lib/systemd/system/cassandra.service 
    mode: 0644 
    force: yes
  notify:
    - reload systemd configuration
    - Restart DSE

- name: Install agent
  package:
    name: datastax-agent
    state: present
  when: dse_opscenter_ip is defined and dse_opscenter_ip != False
  notify:
    - Restart DSE agent

- name: Configure agent
  template:
    src: address.yaml.j2
    dest: /var/lib/datastax-agent/conf/address.yaml
    owner: cassandra
    group: cassandra
    backup: yes
    mode: 0644
  when: dse_opscenter_ip is defined and dse_opscenter_ip != False
  tags: ["config","dse-agents:config"]
  notify:
    - Restart DSE agent

- name: Configure agent
  template:
    src: datastax-agent-env.sh.j2
    dest: /etc/datastax-agent/datastax-agent-env.sh
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: dse_opscenter_ip is defined and dse_opscenter_ip != False
  tags: ["config","dse-agents:config"]
  notify:
    - Restart DSE agent

